### ISSUE TITLE
[bug] - channel not filling in

### ISSUE THREAD

**Issue by johnpapa** [spboyer/social-linker#11]
The url is not adding the tracking links when i click the social media channel

## Steps to repro

1. paste a url into the top box
2. click the Twitter icon

The channel was still blank but the url shows up below like this

![image](https://user-images.githubusercontent.com/1202528/55554944-0df77780-56b2-11e9-8a82-54866ad0ec92.png)

Also, there are no errors in the dev console.

**Comment by spboyer** [comment]
The linker only works for *.microsoft properties.

dev.to would not be shortened. Need to add validation for valid links.

**Comment by johnpapa** [comment]
closed in favor of #14
