### ISSUE TITLE
[bug] - url not adding the tracking when both textboxes are filled manually

### ISSUE THREAD

**Issue by johnpapa** [spboyer/social-linker#12]
The url does not have the tracking when both textboxes are filled manually and i click the button

## steps to repro

1. enter a url
2. enter social
3. enter twitter
4. click `create link`

The url is as shown below

![image](https://user-images.githubusercontent.com/1202528/55555127-7d6d6700-56b2-11e9-91f3-a7a6369bb690.png)

Also, there are no errors in the dev console.

**Comment by spboyer** [comment]
not a valid url for shortening. needs to be a msft link. 
needs validation for proper links

**Comment by johnpapa** [comment]
closed in favor of #14
