### ISSUE TITLE
Use without link shortener

### ISSUE THREAD

**Issue by codemillmatt** [spboyer/social-linker#39]
Latest & greatest version requires a link shortener to be setup. I'd rather not.

It _looks_ like I can get around this by specifying bit.ly and then not enter any credentials.

So what do you think about removing the requirement that a link shortener has to be specified?

**Comment by spboyer** [comment]
Will add a 'none' option in the next release. Seems to have been removed in the latest update

**Comment by spboyer** [comment]
Fixed in https://github.com/spboyer/social-linker/commit/62405817986b4bc55bfc8e951c9fb530431ef820
