### ISSUE TITLE
Tatic and Category Labels Confuse Me

### ISSUE THREAD

**Issue by codemillmatt** [spboyer/social-linker#53]
I have no idea what the **tatic** and **category** labels mean. I mean - the old labels of **event** and **channel** were pretty self-explanatory. But these two are really confusing. Is **tatic** the thing I'm writing about, like _xamarinforms_? Or is it the way I'm spreading the info, like **twitter**?

I'm confused.

**Comment by spboyer** [comment]
These are just terms, they are the same. 

tatic = event
category = channel
